### PR TITLE
fix: use npm co-located with the action node binary

### LINKED ISSUE #234: v6 fails if `npm` does not exist on the runner (GHE)
We're on GHE using our own internal runners and the upgrade from `v5` to `v6` is causing the following error now. This was caught in a [comment](https://github.com/pnpm/action-setup/pull/212#discussion_r3074124457) in the PR that replaced the bundled pnpm binary, cc @benquarmby for catching this.

```
Run pnpm/action-setup@v6
Running self-installer...
  Error: spawn npm ENOENT
      at ChildProcess._handle.onexit (node:internal/child_process:286:19)
      at onErrorNT (node:internal/child_process:484:16)
      at process.processTicksAndRejections (node:internal/process/task_queues:89:21) {
    errno: -2,
    code: 'ENOENT',
    syscall: 'spawn npm',
    path: 'npm',
    spawnargs: [ 'ci' ]
  }
  Error: Error: spawn npm ENOENT
```

This is currently breaking all the workflows at our company.

### PR DESCRIPTION
**Pull request by benquarmby**
Fixes #234 — `spawn npm ENOENT` on GHE self-hosted runners where npm is not on `PATH`.

**Root cause**

#212 introduced `npm ci` as the bootstrap mechanism. On standard GitHub-hosted runners npm is on `PATH`; on GHE self-hosted runners it is not guaranteed to be present.

**Fix**
- Resolve npm via `join(dirname(process.execPath), 'npm'[.cmd])` - ~npm is always co-located with the node binary that runs the action~ CI disproved this statement. An alternative approach was required. See follow up commits for correction.
- Prepend `dirname(process.execPath)` to the child `PATH` so npm's `#!/usr/bin/env node` shebang can resolve node

**Test plan**
- GHE self-hosted runner without npm on `PATH`
- Standard GitHub-hosted Linux, macOS, and Windows runners

### CODE REVIEW

File: src/install-pnpm/run.ts [hunk 1]
```diff
@@ -29,7 +29,12 @@ export async function runSelfInstaller(inputs: Inputs): Promise<number> {
   await writeFile(path.join(dest, 'package.json'), packageJson)
   await writeFile(path.join(dest, 'package-lock.json'), JSON.stringify(lockfile))
 
-  const npmExitCode = await runCommand('npm', ['ci'], { cwd: dest })
+  const nodeDir = path.dirname(process.execPath)
+  // On Windows PATH key casing varies; search case-insensitively.
+  const pathKey = Object.keys(process.env).find(k => k.toUpperCase() === 'PATH') ?? 'PATH'
+  const npmEnv = { ...process.env, [pathKey]: nodeDir + path.delimiter + process.env[pathKey] }
+  const npmBin = process.platform === 'win32' ? 'npm.cmd' : 'npm'
+  const npmExitCode = await runCommand(path.join(nodeDir, npmBin), ['ci'], { cwd: dest, env: npmEnv })
```
Comment (benquarmby) [inline src/install-pnpm/run.ts]: Since the action's node directory has been added to the path, and `npm` (or `npm.cmd`) is a sibling, this could actually be shortened. This is closer to the way it was before:
```suggestion
  const npmExitCode = await runCommand('npm', ['ci'], { cwd: dest, env: npmEnv })
```

**Review by zkochan — APPROVED** [review]

**Comment by zkochan** [comment]
Heads up — I pushed two follow-up commits and want to flag a finding from the CI run.

**`42e75a1` (broken, reverted by `f9d6871`)** attempted to resolve npm via an absolute path: `path.join(dirname(process.execPath), 'npm[.cmd]')`. This is what the original PR description claimed, but it turns out to be **incorrect** for GitHub-hosted runners.

On the runner, `process.execPath` is the runner-bundled node, e.g.:
- Linux: `/home/runner/actions-runner/extracted/externals/node24/bin/node`
- Windows: `C:\actions-runner\cached\2.334.0\externals\node24\bin\node.exe`

That `externals/node24/bin/` directory contains **node only — npm is not there**. The runner ships only the node binary it needs to execute JS actions; npm comes from the runner image's pre-installed Node toolchain and is reachable via `PATH`.

Result of the bad commit:
- Linux/macOS: `Error: spawn /home/runner/.../externals/node24/bin/npm ENOENT`
- Windows: `'C:\actions-runner\...\externals\node24\bin\npm.cmd' is not recognized as an internal or external command`

**`f9d6871`** reverts to spawning `'npm'` and relying on `PATH` lookup (the actual behavior of `5a9e198`, despite its description), while keeping two refinements that are still worthwhile:

1. **Prepend `dirname(process.execPath)` to `PATH`** — needed so npm's `#!/usr/bin/env node` shebang resolves on Linux/macOS in stripped environments where node isn't already on PATH. This is the real GHE self-hosted fix.
2. **Guard against unset `PATH`** — `currentPath ? nodeDir + delimiter + currentPath : nodeDir` avoids `"<dir>:undefined"` leaking in.

If you want, the PR description should probably be updated to drop the "npm is always co-located with the node binary" claim, since CI just disproved it.

**Comment by silas** [comment]
fyi: after this was published, I started getting the following error:

> Unable to resolve action `pnpm/action-setup@v6`, unable to find version `v6`

Updating my workflows to use the exact tag fixed the issue:

> `uses: pnpm/action-setup@v6.0.4`

Anyway, this is probably how you're suppose to reference releases in the action marketplace and is a good change for me anyway, but just a heads up.

**Comment by zkochan** [comment]
The v6 tag was removed just for a moment before I pointed it to a new commit. It should work. However, the recommended way is to use the commit hash. It is the secure way.

**Comment by benquarmby** [comment]
Updated the PR description, and thank you!
